### ISSUE TITLE
expandDepth=0 and isExpanded: true not working

### ISSUE THREAD

**Issue by aaronucsd** [btecu/ember-simple-tree#11]
I'm trying to control to have the checkboxes unchecked by default but none of these options seems to do anything.

**Comment by btecu** [comment]
None of those are used to set the state of the checkbox. The checkboxes are controlled by `isChecked` on each node.

`isExpanded` is used to decide if a node is expanded or not.
`expandDepth` is used to decide if a node is expanded or not globally, however, a more specific `isExpanded` will take precedence.
