### ISSUE TITLE
Checkbox calls "onSelect" then "onCheck"

### ISSUE THREAD

**Issue by ladadeedee** [btecu/ember-simple-tree#13]
With the most recent change, clicking a checkbox fires the "onSelect" action as well as "onCheck". This was not intentional; I did not catch that before making my PR. I have a hack for it involving runtime scheduling but that's not the nicest thing to have in a codebase. Another way is to go back to regular HTML input element for checkboxes rather than input helper, but we lose (easy) indeterminate state.

**Comment by btecu** [comment]
Fixed in 0.5.1.
