### ISSUE TITLE
How to add indentation level for children

### ISSUE THREAD

**Issue by JeanCHilger** [btecu/ember-simple-tree#44]
I would like to add a indentation level for children, but I couldn't find a solution for this in documentation. I am aware that I could achieve this using [blocks](https://github.com/btecu/ember-simple-tree#blocks) but I wouldn't like to have a much complex or inefficient code. Could anyone help me with that?

**Comment by btecu** [comment]
If I remember correctly, the children already have an indentation. Is that not the case?
https://github.com/btecu/ember-simple-tree/blob/master/addon/styles/x-tree.css#L7

**Comment by JeanCHilger** [comment]
I'm using the tree like this in the code:
![image](https://user-images.githubusercontent.com/19687197/93079311-4e5a7380-f662-11ea-8b48-036f27bdc57a.png)

And I'm getting as result this:
![image](https://user-images.githubusercontent.com/19687197/93079843-26b7db00-f663-11ea-8464-432612f60c27.png)

I might be missing something?

**Comment by JeanCHilger** [comment]
I believe that selector (`.tree-node .tree-branch`) isn't being applied, since `.tree-branch` is not - always - within `.tree-node` (thats what happens to me, check the image below). Changing the selector to `.tree .tree-branch` seems to work. That's a bug or I am using the tree wrong?

![image](https://user-images.githubusercontent.com/19687197/93083681-55d14b00-f669-11ea-86ee-4c3fab7e589d.png)

**Comment by btecu** [comment]
@JeanCHilger can you create a repository with a small example? I was checking locally and it seems to be working fine.

**Comment by btecu** [comment]
@JeanCHilger were you able to figure out the issue?

**Comment by JeanCHilger** [comment]
I just used the tree, I don't know exactly why it was buggy for me. Unfortunately, I was working with sensitive data, thus couldn't provide an working example. (I didn't see you asked me for an example before, sorry for not replying).

**Comment by btecu** [comment]
So is it working as intended or did you have to make any changes?

**Comment by JeanCHilger** [comment]
As I stated in the issue, I found problems with indentation of the tree.  I applied some styles and then it worked. I couldn't test with other data though, and since nobody else reported such a problem I believe it is working fine. Thanks anyways.
