### ISSUE TITLE
This addon is not listed on the EmberObserver.

### ISSUE THREAD

**Issue by takshch** [btecu/ember-simple-tree#57]
# Description 
Ember Observer is the place where the addons are rated. It is not easy to find this addon and even after finding this addon, people don't know the ratings and information of this addon.

**Comment by btecu** [comment]
It seems to show up for me, what did you search?
https://emberobserver.com/addons/ember-simple-tree

![image](https://user-images.githubusercontent.com/7517745/123323566-ab455d00-d503-11eb-99d8-38ba83cd2ae5.png)

**Comment by takshch** [comment]
@btecu Thanks but Ember Observer doesn't show ember-simple-tree when i searched `simple tree` .
