### ISSUE TITLE
`chosenId` class is not applied

### ISSUE THREAD

**Issue by oliverlangan** [btecu/ember-simple-tree#61]
While it appears as though the `chosenId` argument is passed down through the components, the [final check in `x-tree-node.js`](https://github.com/btecu/ember-simple-tree/blob/master/addon/components/x-tree-node.js#L18) is incorrect.

```
if (id === this.chosenId) {
```
should be:
```
if (id === this.args.chosenId) {
```

**Comment by oliverlangan** [comment]
related: it would be great if `isChosen` was part of the information yielded to the block.

**Comment by btecu** [comment]
> While it appears as though the `chosenId` argument is passed down through the components, the [final check in `x-tree-node.js`](https://github.com/btecu/ember-simple-tree/blob/master/addon/components/x-tree-node.js#L18) is incorrect.
> 
> ```
> if (id === this.chosenId) {
> ```
> 
> should be:
> 
> ```
> if (id === this.args.chosenId) {
> ```

Can you submit a pull request?
