### ISSUE TITLE
select=(action 'selectNode') does not work on checkbox action

### ISSUE THREAD

**Issue by aaronucsd** [btecu/ember-simple-tree#9]
When i click the checkbox it does not trigger the `select=(action 'selectNode')` action. How can i add an action to the toggle of the checkbox?

**Comment by btecu** [comment]
It appears that right now the checkbox only toggles the value and there is no action:
https://github.com/btecu/ember-simple-tree/blob/master/addon/components/x-tree-node.js#L38

**Comment by aaronucsd** [comment]
Too bad. Cause if i do something like below, not only toggle of checkbox doesn't call an action, the html input i have (too add a comment) triggers the `select` action for every onchange. That's super buggy.


```
        {{#x-tree
          select=(action 'toggleSelection')
          chosenId=selectedNode
          checkable=true
          expandDepth=2
          model=tree as |node|}}
            {{node.name}} ({{node.id}})<br />
            {{#if node.isComment}}
              <input type="text" {{action 'updateComment' node.id on="change"}} placeholder="Comment for {{node.name}}" name="{{node.name}}" id="{{node.id}}" style="border: none;border-bottom: 1px solid grey;margin-left: 30px;width: 800px;">
            {{/if}}
        {{/x-tree}}
```

**Comment by aaronucsd** [comment]
can we get an action trigger for checkbox change?

**Comment by btecu** [comment]
Can you submit a pull request?

**Comment by aaronucsd** [comment]
Sure. I never done the syncing of a changed project to my current project to test. How do i link the local changes of `ember-simple-tree` to my working project to test if the changes works before PR it?
